// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/mano.proto

package proto

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type GetResourcesMessage struct {
	TargetResource       string   `protobuf:"bytes,1,opt,name=target_resource,json=targetResource,proto3" json:"target_resource,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetResourcesMessage) Reset()         { *m = GetResourcesMessage{} }
func (m *GetResourcesMessage) String() string { return proto.CompactTextString(m) }
func (*GetResourcesMessage) ProtoMessage()    {}
func (*GetResourcesMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_93b48816c784b6db, []int{0}
}

func (m *GetResourcesMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetResourcesMessage.Unmarshal(m, b)
}
func (m *GetResourcesMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetResourcesMessage.Marshal(b, m, deterministic)
}
func (m *GetResourcesMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetResourcesMessage.Merge(m, src)
}
func (m *GetResourcesMessage) XXX_Size() int {
	return xxx_messageInfo_GetResourcesMessage.Size(m)
}
func (m *GetResourcesMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_GetResourcesMessage.DiscardUnknown(m)
}

var xxx_messageInfo_GetResourcesMessage proto.InternalMessageInfo

func (m *GetResourcesMessage) GetTargetResource() string {
	if m != nil {
		return m.TargetResource
	}
	return ""
}

type ResourcesResponse struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Value                string   `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ResourcesResponse) Reset()         { *m = ResourcesResponse{} }
func (m *ResourcesResponse) String() string { return proto.CompactTextString(m) }
func (*ResourcesResponse) ProtoMessage()    {}
func (*ResourcesResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_93b48816c784b6db, []int{1}
}

func (m *ResourcesResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ResourcesResponse.Unmarshal(m, b)
}
func (m *ResourcesResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ResourcesResponse.Marshal(b, m, deterministic)
}
func (m *ResourcesResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ResourcesResponse.Merge(m, src)
}
func (m *ResourcesResponse) XXX_Size() int {
	return xxx_messageInfo_ResourcesResponse.Size(m)
}
func (m *ResourcesResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ResourcesResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ResourcesResponse proto.InternalMessageInfo

func (m *ResourcesResponse) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *ResourcesResponse) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

func init() {
	proto.RegisterType((*GetResourcesMessage)(nil), "proto.GetResourcesMessage")
	proto.RegisterType((*ResourcesResponse)(nil), "proto.ResourcesResponse")
}

func init() { proto.RegisterFile("proto/mano.proto", fileDescriptor_93b48816c784b6db) }

var fileDescriptor_93b48816c784b6db = []byte{
	// 164 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0x28, 0x28, 0xca, 0x2f,
	0xc9, 0xd7, 0xcf, 0x4d, 0xcc, 0xcb, 0xd7, 0x03, 0x33, 0x85, 0x58, 0xc1, 0x94, 0x92, 0x1d, 0x97,
	0xb0, 0x7b, 0x6a, 0x49, 0x50, 0x6a, 0x71, 0x7e, 0x69, 0x51, 0x72, 0x6a, 0xb1, 0x6f, 0x6a, 0x71,
	0x71, 0x62, 0x7a, 0xaa, 0x90, 0x3a, 0x17, 0x7f, 0x49, 0x62, 0x51, 0x7a, 0x6a, 0x49, 0x7c, 0x11,
	0x54, 0x4a, 0x82, 0x51, 0x81, 0x51, 0x83, 0x33, 0x88, 0x0f, 0x22, 0x0c, 0xd3, 0xa0, 0x64, 0xc9,
	0x25, 0x08, 0xd7, 0x1c, 0x94, 0x5a, 0x5c, 0x90, 0x9f, 0x57, 0x9c, 0x2a, 0xc4, 0xc7, 0xc5, 0x94,
	0x99, 0x02, 0xd5, 0xc0, 0x94, 0x99, 0x22, 0x24, 0xc2, 0xc5, 0x5a, 0x96, 0x98, 0x53, 0x9a, 0x2a,
	0xc1, 0x04, 0x16, 0x82, 0x70, 0x8c, 0x82, 0xb9, 0x38, 0xe1, 0x5a, 0x85, 0xdc, 0xb8, 0x78, 0x90,
	0xdd, 0x21, 0x24, 0x05, 0x71, 0xa6, 0x1e, 0x16, 0xc7, 0x49, 0x49, 0x40, 0xe5, 0x30, 0x2c, 0x56,
	0x62, 0x48, 0x62, 0x03, 0x4b, 0x19, 0x03, 0x02, 0x00, 0x00, 0xff, 0xff, 0xbf, 0x8c, 0xf6, 0x32,
	0xf1, 0x00, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// ResourcesClient is the client API for Resources service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type ResourcesClient interface {
	GetResources(ctx context.Context, in *GetResourcesMessage, opts ...grpc.CallOption) (*ResourcesResponse, error)
}

type resourcesClient struct {
	cc *grpc.ClientConn
}

func NewResourcesClient(cc *grpc.ClientConn) ResourcesClient {
	return &resourcesClient{cc}
}

func (c *resourcesClient) GetResources(ctx context.Context, in *GetResourcesMessage, opts ...grpc.CallOption) (*ResourcesResponse, error) {
	out := new(ResourcesResponse)
	err := c.cc.Invoke(ctx, "/proto.Resources/GetResources", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ResourcesServer is the server API for Resources service.
type ResourcesServer interface {
	GetResources(context.Context, *GetResourcesMessage) (*ResourcesResponse, error)
}

// UnimplementedResourcesServer can be embedded to have forward compatible implementations.
type UnimplementedResourcesServer struct {
}

func (*UnimplementedResourcesServer) GetResources(ctx context.Context, req *GetResourcesMessage) (*ResourcesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetResources not implemented")
}

func RegisterResourcesServer(s *grpc.Server, srv ResourcesServer) {
	s.RegisterService(&_Resources_serviceDesc, srv)
}

func _Resources_GetResources_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetResourcesMessage)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ResourcesServer).GetResources(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.Resources/GetResources",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ResourcesServer).GetResources(ctx, req.(*GetResourcesMessage))
	}
	return interceptor(ctx, in, info, handler)
}

var _Resources_serviceDesc = grpc.ServiceDesc{
	ServiceName: "proto.Resources",
	HandlerType: (*ResourcesServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetResources",
			Handler:    _Resources_GetResources_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/mano.proto",
}
